# -*- coding: utf-8 -*-
"""NewProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQdxVOCs6qnlLqMUYwOvGv6pjitKO8O0
"""



"""# Data Science Final Project
Points: 1

Exercise 3: Create a markdown cell for an introduction.
markdown
Copy code
## Introduction
This notebook is a final project for the Data Science course. It will cover various aspects of data science, including languages, libraries, tools, and some basic arithmetic operations.
Points: 1

Exercise 4: Create a markdown cell to list data science languages.
markdown
Copy code
## Data Science Languages
- Python
- R
- SQL
- Julia
- Scala
Points: 3

Exercise 5: Create a markdown cell to list data science libraries.
markdown
Copy code
## Data Science Libraries
- Pandas
- NumPy
- Matplotlib
- SciPy
- Scikit-learn
- TensorFlow
- Keras
- PyTorch
Points: 3

Exercise 6: Create a markdown cell with a table of Data Science tools.
markdown
Copy code
## Data Science Tools

| Tool           | Description                                   |
|----------------|-----------------------------------------------|
| Jupyter        | Interactive computing environment             |
| RStudio        | Integrated development environment for R      |
| Apache Hadoop  | Framework for distributed storage and processing |
| Apache Spark   | Unified analytics engine for big data processing |
| Tableau        | Data visualization software                   |
Points: 3

Exercise 7: Create a markdown cell introducing arithmetic expression examples.
markdown
Copy code
## Arithmetic Expression Examples
Below are some examples of arithmetic expressions used in data science.
Points: 1

Exercise 8: Create a code cell to multiply and add numbers.
python
Copy code
# Multiplication and addition
a = 5
b = 4
result = (a * b) + b
result
Points: 2

Exercise 9: Create a code cell to convert minutes to hours.
python
Copy code
# Conversion of minutes to hours
minutes = 150
hours = minutes / 60
hours
Points: 2

Exercise 10: Insert a markdown cell to list Objectives.
markdown
Copy code
## Objectives
- Learn about different data science languages
- Understand various data science libraries
- Explore data science tools
- Perform basic arithmetic operations
- Convert time units
Points: 3

Exercise 11: Create a markdown cell to indicate the Author’s name.
markdown
Copy code
## Author
John Doe

## Author
Ahmed
"""

pd.read_csv('C:\Users\Ahmed Abdelsattar\Documents\heart.csv')